// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/beep.mp3
var resourceBeepMp3Data []byte
var resourceBeepMp3 = &fyne.StaticResource{
	StaticName:    "assets/beep.mp3",
	StaticContent: resourceBeepMp3Data,
}
