#!/bin/bash

MINOR=$(git rev-list --count HEAD 2>/dev/null || echo "0")
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "no-git")
GIT_STR="${MINOR}-${HASH}"

echo "🔨 Embedding Git version : $GIT_STR"

env CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -ldflags "-X 'main.GitVersion=${GIT_STR}' -H windowsgui" -o rummix.exe

if [ $? -eq 0 ]; then
    echo "✅ Compilation successful"
else
    echo "❌ Compilation in error"
    exit 1
fi
