// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed rummix.png
var resourceRamixPngData []byte
var resourceRamixPng = &fyne.StaticResource{
	StaticName:    "rummix.png",
	StaticContent: resourceRamixPngData,
}
