// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/rummix.png
var resourceRummixPngData []byte
var resourceRummixPng = &fyne.StaticResource{
	StaticName:    "assets/rummix.png",
	StaticContent: resourceRummixPngData,
}
