// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/nogood.mp3
var resourceNogoodMp3Data []byte
var resourceNogoodMp3 = &fyne.StaticResource{
	StaticName:    "assets/nogood.mp3",
	StaticContent: resourceNogoodMp3Data,
}
