// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/ok.mp3
var resourceOkMp3Data []byte
var resourceOkMp3 = &fyne.StaticResource{
	StaticName:    "assets/ok.mp3",
	StaticContent: resourceOkMp3Data,
}
