// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed poc.wav
var resourcePocWavData []byte
var resourcePocWav = &fyne.StaticResource{
	StaticName:    "poc.wav",
	StaticContent: resourcePocWavData,
}
