// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/tile.mp3
var resourceTileMp3Data []byte
var resourceTileMp3 = &fyne.StaticResource{
	StaticName:    "assets/tile.mp3",
	StaticContent: resourceTileMp3Data,
}
