// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/winner.mp3
var resourceWinnerMp3Data []byte
var resourceWinnerMp3 = &fyne.StaticResource{
	StaticName:    "assets/winner.mp3",
	StaticContent: resourceWinnerMp3Data,
}
